### ISSUE TITLE
debug and release triple build to same size

### ISSUE THREAD

**Issue by nbsn2** [UbiquityDotNET/Llvm.Libs#1]
Normally the debug  triple build  directory size is 17G.  The release triple build  directory size is 3G.

But if using
```
 .\scripts\Initialize-BuildEnv.ps1
build
```
will result in same 17G size.

**Comment by smaillet** [comment]
Yeah, something is wrong with passing args to the MSVC Ninja build, it's definitely generating more than is desired and into locations that are quite unexpected. On the plus side it is MUCH faster so once this is resolved it just might make a build in AppVeyor work... (I keep hoping as that would make things easier)

**Comment by smaillet** [comment]
It is worth pointing out that once you have the nupkg files you can delete everything else.
